[FIX] Version should be 1.0.1
Fixing this error:
ValueError: git history requires a target version of pbr.version.SemanticVersion(1.0.1), but target version is pbr.version.SemanticVersion(1.0.0)
error in setup command: Error parsing /opt/proxmoxbmc/setup.cfg: ValueError: git history requires a target version of pbr.version.SemanticVersion(1.0.1), but target version is pbr.version.SemanticVersion(1.0.0)